#!/usr/bin/env python3

from utilities import *
from character import Character
import sys

def main():
    arguments = sys.argv[1:]
    count = len(arguments)

    if count >= 2:
        if sys.argv[1] == '-c':
            charURL = parseCharacter(sys.argv[2])
            html = getWebsiteInfo(charURL)
            character = Character(html)
            character.print_info()
    elif sys.argv[1] == '--help':
        file = open('help.txt', 'r')
        print (file.read())
        file.close()

    else:
        print("Invalid command. "
            "Commands should be in the form: ./tibia cli -option -input")
        print("Please refer to ./tibia-cli --help if you are confused.")

main()

